### ISSUE TITLE
2.7.9 wants libjansson.so > 2.4 but is not happy with 2.14

### ISSUE THREAD

**Issue by dlangille** [babelouest/ulfius#227]
When attempting to build on FreeBSD 12.3 and FreeBSD 13.0, I see:

```
-- Found Jansson: /usr/local/lib/libjansson.so (found version "2.14") 
-- Found Jansson: /usr/local/lib/libjansson.so (found suitable version "2.14", minimum required is "2.4") 
```

Logs here:

* FreeBSD 12.3 https://services.unixathome.org/poudriere/data/123amd64-dvl-testing/2022-05-08_19h45m50s/logs/errors/ulfius-2.7.9.log
* FreeBSD 13.0 https://services.unixathome.org/poudriere/build.html?mastername=13amd64-dvl-testing&build=2022-05-08_21h20m09s

It should accept 2.14, see https://github.com/akheron/jansson/tags where it is clear that 2.4 was released on Sep 23, 2012 and 2.1.4 (the latest release) came out on Sep 9, 2021.

This sounds like a math error.

Full details of all versions are in the logs.

**Comment by babelouest** [comment]
I believe this isn't a jansson issue but a wrong version for orcania:

```
  Build step for orcania failed: 1
```

**Comment by dlangille** [comment]
For those following along at home : we discussed over IRC last night. New versions of several ports were created, including `orcania`.

The build continues to fail with a duplicate symbol:

https://services.unixathome.org/poudriere/data/13amd64-dvl-testing/2022-05-09_01h42m36s/logs/errors/glewlwyd-2.7.0.log
