### ISSUE TITLE
Painful to build on Centos 6.5 

### ISSUE THREAD

**Issue by msnyder415** [babelouest/ulfius#2]
Hi Babelouest. Good job on a very awesome REST framework. 
It was easy to install and use on Centos 7. 

I have one issue: this is painful to install on systems that do not support > libcurl 20.
I have a few 6.5 machines that will want to run this, and the centos repos do not have anything newer than libcurl 7.19. 

These kind of errors come up - 
u_send_request.c:724: error: ‘CURLOPT_MAIL_RCPT’ undeclared (first use in this function)
u_send_request.c:724: warning: type defaults to ‘int’ in declaration of ‘_curl_opt’
make[1]: *** [u_send_request.o] Error 1
make[1]: Leaving directory `/home/xxx/ulfius/src'
make: *** [libulfius.so] Error 2

Since I am not using SMTP in my project, I was able to disable the entire ulfius_send_smtp_email function. Do you have any suggestions for dealing with this?

Maybe a configure option to disable SMTP features?
Or some older CURLOPT flag for backwards compat? 

Thanks!

**Comment by babelouest** [comment]
Hello,

Thanks for your feedback. I wanted to reproduce your bug to be able to fix it somehow but I couldn't find any suitable Centos 6.5 image for virtualbox. I could see that indeed, it works fine on Centos 7.

The libcurl documentation doesn't say much about `CURLOPT_MAIL_RCPT`, except that this option is available since 7.20: https://curl.haxx.se/libcurl/c/CURLOPT_MAIL_RCPT.html

In order to make a workaround for your problem, without breaking existing configurations, I made a small fix to be able to easily disable this function. Although it's still enabled by default: https://github.com/babelouest/ulfius/commit/a5caad9fc873e8f4ce1c0c44be0991a6eff3d9a6

Let me know if this patch fixes your problem, don't forget to update your `src/Makefile` first, see updated `README.md` : https://github.com/babelouest/ulfius/commit/6d189b3892b20f12b08acae03efe0de176f0c27f

**Comment by babelouest** [comment]
@msnyder415 , any update on the patch? Just to know if I can close the issue?
