### ISSUE TITLE
[Issue] ulfius won't compile

### ISSUE THREAD

**Issue by DL4OCE** [babelouest/ulfius#276]
**Describe the issue**
Cannot create either one o the example apps nor a derived own project.
Won't compile with gcc 11.4.0.

**To Reproduce**
$> make
cd ../../src && make debug JANSSONFLAG=1 CURLFLAG=1 GNUTLSFLAG=1
make[1]: Verzeichnis „/home/arne/dev/hamlib_feature_rest_api/ulfius/ulfius/src“ wird betreten
gcc -c -pedantic -std=gnu99 -fPIC -Wall -Werror -Wextra -Wconversion -Wpedantic -D_REENTRANT -I../include -DDEBUG -g -O0  u_map.c
u_map.c: In function ‘u_map_put_binary’:
u_map.c:159:40: error: implicit declaration of function ‘o_strnullempty’ [-Werror=implicit-function-declaration]
  159 |   if (u_map != NULL && key != NULL && !o_strnullempty(key) && (offset+length+1) <= SIZE_MAX) {
      |                                        ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:197: u_map.o] Fehler 1
make[1]: Verzeichnis „/home/arne/dev/hamlib_feature_rest_api/ulfius/ulfius/src“ wird verlassen
make: *** [Makefile:37: ../../src/libulfius.so] Fehler 2

**Expected behavior**
The rograms should be compiled
**Screenshots**
see above
**System (please complete the following information):**
- kubuntu 22.04
- gcc 11.4.0
 - Ulfius Version 2.7.15
 - git clone
 - If applicable, what option did you use to build Ulfius [e.g. disable GnuTLS, disable Websocket]: default (Makefile settings)

**Comment by DL4OCE** [comment]
I'm sorry, didn't get the rereqs correct

**Comment by DL4OCE** [comment]
Can be closed
